redis:
  image: redis
  ports:
    - "6379"

web:
  build: .
  volumes:
    - /tmp/nginx/:/var/log/nginx
    # - .:/myapp
  ports:
    - "80:80"
    - "4567:4567"
  links:
    - redis
  environment:
    - REDIS_HOST=redis
